export type ScreenshotPluginRecord = {
  name: string;
  description: string;
  category:
    | "strategy"
    | "create"
    | "build"
    | "sales"
    | "analyse"
    | "utility"
    | "travel"
    | "design"
    | "media"
    | "productivity"
    | "documents"
    | "research"
    | "integrations";
};

type CatalogRow = readonly [name: string, description: string];

function group(
  category: ScreenshotPluginRecord["category"],
  rows: readonly CatalogRow[],
): ScreenshotPluginRecord[] {
  return rows.map(([name, description]) => ({ name, description, category }));
}

/**
 * Manually verified transcription of the plugin names and short descriptions
 * visible in Olaf's supplied screenshots. Availability can change; these are
 * catalog references and do not imply that a plugin is installed or connected.
 */
export const screenshotPluginRecords: ScreenshotPluginRecord[] = [
  ...group("design", [
    ["UX Pilot", "Generate wireframes and UI"],
    ["Product Design", "Explore and prototype ideas"],
    ["Pablooo.club Benchmark library", "Benchmark 10k+ screenshots"],
    ["Maze", "Pull your Maze research"],
    ["Uxia", "AI usability testing"],
    ["Font Pairing: Design & Brands", "Generate UI typography combos"],
    ["B&A: Draw Sketches", "Draw and visualize ideas"],
    ["Gradient Maker - Linear Color", "Generate background CSS and images"],
    ["Alpix", "Draw pixel art on a shared canvas"],
    ["PoolVisionIA", "Visualize your pool"],
    ["Whiteboard by Athena AI", "Collaborative whiteboard AI"],
    ["WalkMyPlan – Floor Plans in 3D", "Home design by chat, in 3D"],
    ["Looking Glass", "Turn outfits into prompts"],
    ["AI Graphic Design", "Graphics, slides and moodboards"],
    ["Impeccable", "Design and refine interfaces"],
    ["Designly", "Create better visual designs"],
    ["Supericons", "Find the right icon faster"],
    ["Kive", "Create product visuals"],
    ["B&A: Sketch", "Draw and visualize ideas"],
    ["Pixelixe", "Create and edit graphics"],
    ["Dovetail", "Turn feedback into decisions"],
    ["B&A: Diagrams", "Create diagrams visually"],
    ["Canvs.io whiteboard", "Diagrams, mind maps and more"],
    ["Lucid", "Ideate, diagram and align teams"],
    ["Whimsical", "Create diagrams and wireframes"],
    ["Make A Viz", "Create and edit flowcharts"],
    ["Amazing Drawing", "Sketch and draft art and design"],
    ["AI Color Picker - Design Tool", "Brand, graphic, logo and website colors"],
    ["MyFonts", "AI font search and discovery"],
    ["Vulca", "Structure visual work"],
    ["Mapify", "Turn anything into mind maps"],
    ["MindMap", "Create mind map diagrams"],
    ["Figma", "Design-to-code workflows"],
  ]),
  ...group("media", [
    ["VisualSong", "Create music-reactive visuals"],
    ["BlitzReels", "Create short videos"],
    ["Magnific", "Create images, video and designs"],
    ["Glinded for Birthday Videos", "Anniversary and family slideshow"],
    ["HyperFrames by HeyGen", "Write HTML and render video"],
    ["Picsart", "Generate videos, images and audio"],
    ["Remotion", "Make videos agentically"],
    ["Unsplash", "Find and use free HD images"],
    ["Martini", "Collaborative filmmaking"],
    ["Morphix", "Create images, video and audio"],
    ["Montage", "Import videos and cut clips"],
    ["Pixlie", "Write cinematic text-to-video"],
    ["Instavar Remotion Templates", "Make videos from templates"],
    ["Yaps Video Clipping", "Remove dead space from videos"],
    ["Yaps Video Captions", "Add captions to any video"],
    ["中文口播智能粗剪", "Clean spoken-Chinese recordings and remove verbal slips"],
    ["Deep Art AI", "Edit and create videos and images"],
    ["PixVerse", "Create AI media with PixVerse"],
    ["Faces", "Build slide decks"],
    ["AI Video Maker", "Make videos from a text prompt"],
    ["AI Voice Generator", "Create AI voiceovers"],
    ["OpenArt", "Create images and videos"],
    ["Runway", "Generate videos"],
    ["Pixum", "Create and find photo products"],
    ["CreativeClaw", "Create branded images and video"],
    ["YouCam (beta)", "Analyze, edit and transform photos"],
    ["PrintTiler", "Make tiled posters"],
    ["Higgsfield", "Use image and video models"],
    ["TalkGen", "AI talking avatar generator"],
    ["Adobe", "Design, combine and edit"],
    ["DepositPhotos", "Find and create visual assets"],
    ["123 Piano", "Play keyboard music and learn"],
    ["Presentations.AI", "Create slides and decks"],
    ["Flipsnack", "Create interactive flipbooks"],
    ["Photo9", "Design and print photo books"],
    ["Flipbook - Publuu", "Convert PDF to flipbook"],
    ["Sequel.io", "Repurpose webinar content"],
    ["Subdivide", "Metronome and click tracks"],
    ["Hypernatural", "Create and edit AI videos"],
    ["Yaps Background Remover", "Remove image backgrounds"],
    ["Yaps Audio Cleaner", "Remove noise and enhance speech"],
    ["Awesome Slides", "Slides with video and voiceover"],
    ["Speechify", "Listen with generated voices"],
    ["Awesome Record (voice + sound)", "Record voice and sound"],
    ["HeyGen", "Create AI videos"],
  ]),
  ...group("build", [
    ["WebsitePublisher", "Create sites via conversation"],
    ["HZplan", "Create and edit floor plans"],
    ["B12 Website Generator", "Create a website in seconds"],
    ["Instant Website", "Build websites in seconds"],
    ["Dazzly", "Build websites with chat"],
    ["VIXNODE", "Build websites with AI"],
    ["Grapes Studio", "Create websites and emails"],
    ["Insta Website Builder", "Create a website instantly"],
    ["Jimdo", "Create your website"],
    ["AppDeploy", "Build and deploy web apps"],
    ["Lovable", "Build apps and websites"],
    ["Netlify", "Build and deploy on Netlify"],
    ["Base44", "Build apps and websites with AI"],
    ["OpenAI Developers", "Develop AI apps, agents and ChatGPT integrations"],
    ["Supabase", "Manage and query databases"],
    ["Vercel", "Build and deploy web apps and agents"],
  ]),
  ...group("create", [
    ["Idea Generator", "Crossbreed ideas creatively"],
    ["Email Love", "Build export-ready emails"],
    ["Agentic Slides by SlidesGPT", "Make presentations and slides"],
    ["RewriteLy Humanizer", "Rewrite AI text naturally"],
    ["Manus", "Create slides, websites and video"],
    ["Goodnotes", "Turn AI insights into a document"],
    ["Wordy - Highlight+Annotate Text", "Writing documents, feedback and analysis"],
    ["Truffle Journal", "Capture journal entries and structured notes"],
  ]),
  ...group("documents", [
    ["ResumeBoost", "Optimize resumes and cover letters"],
    ["Smallpdf", "Work with PDFs"],
    ["Foxit PDF Editor", "Edit and share PDFs"],
    ["Kickresume", "Generate ATS-friendly resumes"],
    ["PDF Editor PRO by Playgram", "Edit and annotate PDF documents"],
    ["BluTranslate", "Translate PDFs and documents"],
    ["Adobe Acrobat", "Edit and organize PDFs"],
    ["Resume Builder", "Analyze and refine your resume"],
    ["Upplai", "Check resume ATS score"],
    ["AccurateScribe.ai - Transcribe", "Transcribe audio to text"],
    ["Sider Recorder & Transcriber", "Record, transcribe and summarize"],
    ["CamScanner", "OCR and extract text for AI"],
    ["Formula Genius", "Work with Excel, Sheets, SQL and regex"],
    ["CVpop - Resume & CV Builder", "Create resumes and CVs"],
    ["AnyPDF - Your PDF Converter", "Convert PDFs with one prompt"],
  ]),
  ...group("productivity", [
    ["Dunzo - Task Assistant", "Capture and manage tasks"],
    ["Taskaid AI", "Manage tasks and plans"],
    ["Outliner", "Create and edit outlines"],
    ["NoteItHub", "Turn chats into tasks and notes"],
    ["Circleback", "Access context from meetings"],
    ["Read AI", "Capture notes from meetings"],
    ["Structured", "All-in-one daily planner"],
    ["Reclaim.ai", "Manage your calendar and tasks"],
    ["Jam", "Screen record with context"],
    ["Hjarni Notes", "Your notes and AI memory"],
    ["tl;dv", "Fetch your meetings data"],
    ["MeetGeek", "Search meeting transcripts"],
    ["Stable Baseline", "Documentation, plans and boards"],
    ["Spinach AI", "Search meeting notes and data"],
    ["Asana", "Turn chats into actions"],
    ["Monday.com", "Manage work in monday.com"],
    ["Linear", "Plan and build products"],
    ["Atlassian Rovo", "Manage Jira and Confluence"],
    ["ClickUp", "Use Codex as a ClickUp command center"],
    ["Basecamp", "Connect to Basecamp"],
  ]),
  ...group("research", [
    ["FashionTrendAI", "Analyze fashion trends"],
    ["Flaim Fantasy", "Fantasy sports analysis"],
    ["Ranked AI", "Manage SEO and PPC"],
    ["Consensus", "Explore scientific research"],
    ["Hugging Face", "Inspect models, datasets and Spaces"],
    ["Binance", "Explore Binance market data"],
    ["Scite", "Find answers grounded in science"],
    ["vidIQ", "YouTube stats and keywords"],
    ["Sider Scholar", "Search 350M+ papers, save and chat"],
    ["Semrush", "Research keywords and traffic"],
    ["PostHog", "Analyze product data"],
    ["Alpaca", "Market data for stocks and crypto"],
    ["Public Equity Investing", "Public equity investment research"],
    ["Investment Banking", "M&A, capital markets and valuation workflows"],
  ]),
  ...group("sales", [
    ["Linkly URL Shortener", "URL shortener for marketers"],
    ["Lnk.Bio", "Add, edit and style your link page"],
    ["Formbyte", "Create, share and analyze forms"],
    ["Weavely Forms & Surveys", "Create forms and surveys"],
    ["Help Scout", "Connect and sync Help Scout mailboxes"],
    ["Calendly", "Manage bookings and availability"],
    ["CALL-E", "Make phone calls for you"],
    ["Kopi - Shopify Email Creator", "Design marketing emails in HTML"],
    ["HubSpot", "Turn HubSpot insights into action"],
    ["Airtable", "Add structured data to ChatGPT"],
    ["Stripe", "Accept payments"],
    ["Apollo.io", "Find buyers and close deals"],
    ["Attio", "Manage your CRM with ChatGPT"],
    ["Sales", "Practical workflows for sellers and sales teams"],
    ["Shopify", "Build and manage your store"],
    ["Dex", "Manage your Dex CRM"],
  ]),
  ...group("analyse", [
    ["Hook Layer", "Find and analyze viral content"],
    ["Norton", "Verify scams from web and email"],
    ["Happenstance", "Search your network"],
    ["Responsive", "Find answers from your content"],
    ["Tarot", "Tarot reading and divination"],
  ]),
  ...group("integrations", [
    ["Opera Browser Connector", "Connect with the Opera browser"],
    ["Dropbox Dash", "AI that understands your work"],
    ["AI Wisebase", "Chat with your knowledge base"],
    ["Datasite", "Manage your M&A data room"],
    ["DocuSign", "Manage contracts from ChatGPT"],
    ["Krisp", "Add meeting context to chats"],
    ["Voicenotes", "Interact with your Voicenotes"],
    ["Zite", "Manage and query Zite data"],
    ["Cognito MCP", "Manage Cognito forms"],
    ["MarcoPolo", "Secure AI data workspace"],
    ["Google Contacts", "Reference saved contact details"],
    ["Granola", "Add your meeting context"],
    ["Box", "Search and reference your documents"],
    ["GitHub", "Triage PRs, issues, CI and publish flows"],
    ["Google Drive", "Work across Drive, Docs, Sheets and Slides"],
    ["Slack", "Read and manage Slack"],
    ["Notion", "Notion workflows for specs and research"],
    ["Outlook Email", "Triage Outlook inboxes and drafts"],
    ["SharePoint", "Summarize SharePoint sites and content"],
    ["Teams", "Summarize Teams and draft follow-ups"],
    ["Outlook Calendar", "Manage Outlook schedules"],
    ["Dropbox", "Access, save and share files"],
  ]),
  ...group("utility", [
    ["TRIGGERcmd", "Run commands on your computers"],
    ["Aha!", "Connect to Aha! in Codex"],
    ["A-Z Links", "Create accessible links in chat"],
    ["QRCM", "Create and customize QR codes"],
    ["Docket", "Product knowledge assistant"],
    ["Empirical", "Memory vault"],
    ["Prompt Perfect", "Create and manage prompts"],
    ["Xmind", "Mind mapping and idea organization"],
    ["Simple SoapCalc", "Lye calculations"],
    ["Network Solutions", "Search, check and secure domains"],
    ["ButlerBrain", "Intelligent memory"],
    ["SignNow", "Automate e-signature workflows"],
  ]),
];
